'use strict';

/**
 * Generates the brand artwork from the palettes.
 *
 *   node ./scripts/brand.js
 *
 * The mark is unchanged from the one drawn by hand in 2024 — a planet, an
 * orbit that crosses in front of it once, and a satellite. Only the colours are
 * computed. They used to be hard-coded hexes, which meant every palette change
 * silently left the icon showing the previous theme's colours; the palette has
 * moved three times since the icon was drawn.
 *
 * Same rule as the theme itself: no literal colour lives here. Everything
 * resolves out of a token file, so `yarn brand && yarn assets` is what makes
 * the artwork true again after a palette change.
 *
 * The dark artwork is Nebula's, because Nebula is the theme the extension leads
 * with. The light artwork is Daybreak's.
 */

const fs = require('fs');
const path = require('path');
const { createResolver } = require('./resolve');
const { readSource } = require('./yaml');

const ROOT = path.join(__dirname, '..');
const ASSETS = path.join(ROOT, 'assets');

const MONO = 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace';

/** The mark, at 128×128. Drawn twice: once for the icon, once inside the banner. */
function mark(t, dx = 0, dy = 0) {
    const at = !dx && !dy ? '' : ` transform="translate(${dx} ${dy})"`;
    return `<g${at}>
    <!-- Orbit, far side. Drawn first so the planet occludes it. -->
    <g transform="rotate(-28 64 64)">
      <path d="M12 64 A 52 22 0 0 1 116 64" fill="none" stroke="${t['accent.base']}" stroke-width="6"/>
    </g>
    <!-- Planet -->
    <circle cx="64" cy="70" r="29" fill="${t['accent.solid']}"/>
    <!-- Orbit, near side, crossing in front. This single occlusion is what makes
         the ellipse read as an orbit rather than a flat ring. -->
    <g transform="rotate(-28 64 64)">
      <path d="M116 64 A 52 22 0 0 1 12 64" fill="none" stroke="${t['accent.base']}" stroke-width="6"/>
    </g>
    <!-- Satellite: the palette's second highlight -->
    <circle cx="93" cy="33" r="8.5" fill="${t['role.keyword']}"/>
  </g>`;
}

function icon(t, ground) {
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" width="128" height="128" role="img" aria-label="Satellite">
  <title>Satellite</title>
  <!-- Generated by scripts/brand.js — edit the palette, not this file. -->
  <!-- The icon is full-bleed, so it carries its own background rather than
       relying on the Marketplace tile. -->
  <rect width="128" height="128" fill="${ground}"/>
  ${mark(t)}
</svg>
`;
}

/** Deterministic star field — same stars every run, so the PNG is stable. */
function stars(t, seed = 7) {
    let s = seed;
    const rand = () => (s = (s * 1103515245 + 12345) & 0x7fffffff) / 0x7fffffff;
    const out = [];
    for (let i = 0; i < 26; i++) {
        const cx = 690 + rand() * 570;
        const cy = 24 + rand() * 272;
        // Keep the field out of the planet's circle so it does not read as noise.
        const d = Math.hypot(cx - 1080, cy - 196);
        if (d < 104) continue;
        out.push(
            `<circle cx="${cx.toFixed(0)}" cy="${cy.toFixed(0)}" r="${(1.4 + rand() * 1.3).toFixed(1)}"/>`,
        );
    }
    return `<g opacity=".5" fill="${t['text.subtle']}">${out.join('')}</g>`;
}

function banner(t, ground, tagline) {
    // The six syntax roles, in ladder order — doubles as a palette preview.
    const strip = [
        'role.keyword',
        'role.string',
        'role.function',
        'role.tag',
        'role.constant',
        'role.variable',
    ]
        .map(
            (role, i) =>
                `<rect x="${234 + i * 58}" y="272" width="52" height="8" rx="4" fill="${t[role]}"/>`,
        )
        .join('\n    ');

    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 320" width="1280" height="320" role="img" aria-label="Satellite — a space-inspired theme for VS Code">
  <title>Satellite</title>
  <!-- Generated by scripts/brand.js — edit the palette, not this file. -->
  <defs>
    <linearGradient id="ground" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="${ground}"/>
      <stop offset="1" stop-color="${t['surface.base']}"/>
    </linearGradient>
  </defs>
  <rect width="1280" height="320" fill="url(#ground)"/>

  ${stars(t)}

  <!-- the mark, blown up: same occlusion, same three colours -->
  <g transform="rotate(-18 1080 170)">
    <path d="M850 170 A 230 96 0 0 1 1310 170" fill="none" stroke="${t['accent.base']}" stroke-width="4" opacity=".6"/>
  </g>
  <circle cx="1080" cy="196" r="78" fill="${t['accent.solid']}"/>
  <g transform="rotate(-18 1080 170)">
    <path d="M1310 170 A 230 96 0 0 1 850 170" fill="none" stroke="${t['accent.base']}" stroke-width="4" opacity=".6"/>
  </g>
  <circle cx="1246" cy="106" r="12" fill="${t['role.keyword']}"/>

  <!-- lockup -->
  ${mark(t, 72, 96)}

  <text x="232" y="158" font-family="${MONO}"
        font-size="60" font-weight="600" letter-spacing="-2" fill="${t['text.default']}">Satellite</text>
  <text x="234" y="196" font-family="${MONO}"
        font-size="19" fill="${t['text.subtle']}">${tagline}</text>

  <g font-family="${MONO}" font-size="15">
    <rect x="234" y="222" width="95" height="26" rx="13" fill="${t['accent.solid']}"/>
    <text x="250" y="240" fill="${t['text.onAccent']}">WCAG AA</text>
    <rect x="341" y="222" width="230" height="26" rx="13" fill="${t['surface.raised']}"/>
    <text x="357" y="240" fill="${t['text.muted']}">colour-vision verified</text>
  </g>

  <g>
    ${strip}
  </g>
</svg>
`;
}

const TAGLINE = 'Five variants for VS Code — verified on every build';

function build() {
    const dark = createResolver(readSource('tokens-nebula.yml')).table;
    const light = createResolver(readSource('tokens-daybreak.yml')).table;

    const files = {
        'icon.svg': icon(dark, dark['surface.deep']),
        // The light mark sits on white rather than on the theme's own ground, so
        // it does not vanish into a light Marketplace tile.
        'icon-light.svg': icon(light, '#FFFFFF'),
        'banner.svg': banner(dark, dark['surface.deep'], TAGLINE),
        'banner-light.svg': banner(light, light['surface.deep'], TAGLINE),
    };

    const written = [];
    for (const [name, source] of Object.entries(files)) {
        fs.writeFileSync(path.join(ASSETS, name), source);
        written.push({ name, bytes: Buffer.byteLength(source) });
    }
    return written;
}

module.exports = { build };

if (require.main === module) {
    try {
        for (const f of build()) {
            process.stdout.write(
                `  ok     assets/${f.name.padEnd(22)} ${(f.bytes / 1024).toFixed(1)} KB\n`,
            );
        }
        process.stdout.write('\n  Now run `yarn assets` to rasterise these to PNG.\n');
    } catch (err) {
        process.stderr.write(`\nBrand generation failed: ${err.message}\n`);
        process.exit(1);
    }
}
